---

homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
homebrew_repository: "{{ homebrew_prefix }}/Homebrew"
homebrew_cache: "{{ ansible_env.HOME }}/Library/Caches/Homebrew"

homebrew_user: "{{ ansible_user_id }}"
homebrew_group: "admin"

brew_git_repo: "https://github.com/Homebrew/brew"
