---

- name: Empty {{ name }} exports
  template:
    src: exports.j2
    dest: "{{ ansible_user_dir }}/.profile.d/{{ name }}.sh"

- name: Add {{ name }} exports
  lineinfile:
    path: "{{ ansible_user_dir }}/.profile.d/{{ name }}.sh"
    insertafter: "# Start Ansible Managed Exports"
    line: "export {{ item.name }}={{ item.value }}"
  with_items: "{{ exports }}"
