---

- name: Empty {{ config.name }} exports
  template:
    src: exports.j2
    dest: "{{ ansible_facts['user_dir'] }}/.profile.d/{{ config.name }}.sh"

- name: Add {{ config.name }} exports
  lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/.profile.d/{{ config.name }}.sh"
    line: "export {{ item.name }}={{ item.value }}"
  with_items: "{{ config.exports }}"
