---

- import_playbook: setup.yml

- hosts: default
  collections:
    - rkhmelichek.developer
  environment:
    PATH: "{{ path | default(ansible_env.PATH) }}"
  roles:
    - role: rkhmelichek.ssh-keys
      ssh_keys: "{{ my_ssh_keys }}"
      tags: ssh-keys
    - role: config-ssh
      configs: "{{ config_ssh }}"
      tags: config-ssh
